### ISSUE TITLE
怎样搭友链啊qwq

### ISSUE THREAD

**Issue by CGHeavenHealer** [amehime/hexo-theme-shoka#36]
rt

**Comment by DreamStar1996** [comment]
shocka的博客，特殊功能下有

**Comment by monkey-HH** [comment]
https://shoka.lostyu.me/computer-science/note/theme-shoka-doc/special/
参考下这里

**Comment by UniStart2** [comment]
### 根据主题配置文件中名在source中创建对应的文件夹放入index.md，_data.yml就好了
---
例如下面是我的主题配置文件_config.shoka.yml
```yaml 
menu:
  ... # 其他目录略
  links: /links/ || magic
```
在root/source文件夹下创建一个links文件下，并新建index.md和_data.yml，index.md最后会被渲染成html页面并显示，_data.yml用于保存你需要展示的链接，你可以在之前建立的index.md中通过{% linksfile 数据文件路径 %}的方式，引入你保存在yaml中的链接
---
举例
1. root/source/links/index.md
```markdown
----
title: 链接
keywords: 链接
description: 链接
copyright: false
---

# 云服务
{% linksfile links/_cloudservice.yml %}

# 网站
{% linksfile links/_website.yml %}
```

2. root/source/links/_cloudservice.yml
```yaml
- site: AWS.  # 链接名称
  owner: Aamzon Web Service
  url: https://aws.amazon.com/cn  # 链接网址
  desc: AWS 云服务-专业的大数据和云计算服务以及云解决方案提供商 # 链接网站描述
  image: "" # 链接左侧图标，不填会有一张默认空缺图片显示
  color: "#f07c82" # 链接名称文字的颜色
```

4. root/source/links/_website.yml
```yaml
- site: daily.dev
  owner: daily.dev
  url: https://daily.dev
  desc: ALL DEVELOPER NEWS IN ONE PLACE
  image: ""
  color: "#131824"
```
