### ISSUE TITLE
执行hexo g或hexo s命令时报错

### ISSUE THREAD

**Issue by YanDao0313** [amehime/hexo-theme-shoka#75]
![img](https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5115/04baa7902c480ec370cf8f9a0310bb1.png)

如图

全程文本：

```
PS C:\Users\32011\Documents\GitHub\daoblog.top> hexo g
INFO  Validating config
INFO  Start processing
Prism's Diff Highlight plugin requires the Diff language definition (prism-diff.js).Make sure the language definition is loaded or use Prism's Autoloader plugin.
FATAL Something's wrong. Maybe you can find the solution here: https://hexo.io/docs/troubleshooting.html
TypeError: Cannot read properties of null (reading 'valine')
    at Hexo.<anonymous> (C:\Users\32011\Documents\GitHub\daoblog.top\themes\shoka\scripts\generaters\script.js:24:32)
    at Hexo.tryCatcher (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\util.js:16:23)
    at Hexo.<anonymous> (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\method.js:15:34)
    at C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\hexo\lib\hexo\index.js:407:22
    at tryCatcher (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\util.js:16:23)
    at MappingPromiseArray._promiseFulfilled (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\map.js:68:38)
    at PromiseArray._iterate (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\promise_array.js:115:31)
    at MappingPromiseArray.init (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\promise_array.js:79:10)
    at MappingPromiseArray._asyncInit (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\map.js:37:10)
    at _drainQueueStep (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\async.js:97:12)
    at _drainQueue (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\async.js:86:9)
    at Async._drainQueues (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\async.js:102:5)
    at Async.drainQueues [as _onImmediate] (C:\Users\32011\Documents\GitHub\daoblog.top\node_modules\bluebird\js\release\async.js:15:14)
    at process.processImmediate (node:internal/timers:471:21)
```

----------

> 附件

站点配置文件：

```yaml
# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: Yandao's Blog
subtitle: ''
description: "Yandao's Hexo Blog"
keywords: Yandao, Hexo, blog
author: Yandao
language: zh-CN
timezone: 'Asia/Shanghai'

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: 'https://www.daoblog.top/'
permalink: /post/:title.html
permalink_defaults: :title/
pretty_urls:
  # trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  # trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ''
filename_case: 0
render_drafts: false
post_asset_folder: false
relative_link: false
future: true
highlight:
  enable: false
  line_number: true
  auto_detect: true
  tab_replace: ''
  wrap: true
  hljs: false
prismjs:
  enable: false
  #preprocess: true
  #line_number: true
  #tab_replace: ''

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
# index_generator:
#   path: ''
#   per_page: 10
#   order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
  杂谈: note
  教程: course
  Doc: doc

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: 'mtime'

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: shoka

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: ''

# edit for Theme.shoka
autoprefixer:
  exclude:
    - '*.min.css'

markdown:
  render: # 渲染器设置
    html: false # 过滤 HTML 标签
    xhtmlOut: true # 使用 '/' 来闭合单标签 （比如 <br />）。
    breaks: true # 转换段落里的 '\n' 到 <br>。
    linkify: true # 将类似 URL 的文本自动转换为链接。
    typographer: 
    quotes: '“”‘’'
  plugins: # markdown-it 插件设置
    - plugin:
        name: markdown-it-toc-and-anchor
        enable: true
        options: # 文章目录以及锚点应用的 class 名称，shoka 主题必须设置成这样
          tocClassName: 'toc'
          anchorClassName: 'anchor'
    - plugin:
        name: markdown-it-multimd-table
        enable: true
        options:
          multiline: true
          rowspan: true
          headerless: true
    - plugin:
        name: ./markdown-it-furigana
        enable: true
        options:
          fallbackParens: "()"
    - plugin:
        name: ./markdown-it-spoiler
        enable: true
        options:
          title: "你知道得太多了"

minify:
  html:
    enable: true
    exclude: # 排除 hexo-feed 用到的模板文件
      - '**/json.ejs'
      - '**/atom.ejs'
      - '**/rss.ejs'
  css:
    enable: true
    exclude:
      - '**/*.min.css'
  js:
    enable: true
    mangle:
      toplevel: true
    output:
    compress:
    exclude:
      - '**/*.min.js'

# autoprefixer:
#   exclude:
#     - '*.min.css'

algolia:
  appId: 1*** #Your appId
  apiKey: 2**** #Your apiKey
  adminApiKey: 78*****4eb1 #Your adminApiKey
  chunkSize: 5000
  indexName: #"shoka"
  fields:
    - title #必须配置
    - path #必须配置
    - categories #推荐配置
    - content:strip:truncate,0,2000
    - gallery
    - photos
    - tags

feed:
    limit: 20
    order_by: "-date"
    tag_dir: false
    category_dir: false
    rss:
        enable: true
        template: "themes/shoka/layout/_alternate/rss.ejs"
        output: "rss.xml"
    atom:
        enable: true
        template: "themes/shoka/layout/_alternate/atom.ejs"
        output: "atom.xml"
    jsonFeed:
        enable: true
        template: "themes/shoka/layout/_alternate/json.ejs"
        output: "feed.json"
```

主题配置文件：

````yaml
alternate: Yandao

# Assets
statics: / #//cdn.jsdelivr.net/gh/amehime/shoka@latest/

darkmode: true

auto_scroll: true

# project of https://www.iconfont.cn/
# //at.alicdn.com/t/font_1832207_c8i9n1ulxlt.css => 1832207_c8i9n1ulxlt
iconfont: "1832207_c8i9n1ulxlt"

font:
  enable: true
  # Font options:
  # `external: true` will load this font family from `host` above.
  # `family: Times New Roman`. Without any quotes.
  # `size: x.x`. Use `em` as unit. Default: 1 (16px)

  # Global font settings used for all elements inside <body>.
  global:
    external: true
    family: Mulish
    size:

  # Font settings for alternate title.
  logo:
    external: true
    family: Fredericka the Great
    size: 3.5

  # Font settings for site title.
  title:
    external: true
    family: Noto Serif JP
    size: 2.5

  # Font settings for headlines (<h1> to <h6>).
  headings:
    external: true
    family: Noto Serif SC
    size:

  # Font settings for posts.
  posts:
    external: true
    family:

  # Font settings for <code> and code blocks.
  codes:
    external: true
    family: Inconsolata

open_graph:
  #twitter_id:
  #google_plus:
  #fb_admins:
  #fb_app_id:

menu:
  home: / || home
  posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
  friends: /friends/ || heart

# Social Links
# Usage: `Key: permalink || icon || color`
# Key is the link label showing to end users.
# Value before `||` delimiter is the target permalink,
# secend value is the name of Font icon.
social:
  github: https://github.com/YanDao0313|| github || "#191717"
  #google: https://plus.google.com/yourname || google
  twitter: https://twitter.com/YanDao0313 || twitter || "#00aff0"
  bilibili: https://space.bilibili.com/1639079419/ || bilibili || "#66ccff"
  #zhihu: https://www.zhihu.com/people/rurismzk || zhihu || "#1e88e5"
  #music: https://music.163.com/#/user/home?id=12886823 || cloud-music || "#e60026"
  #weibo: https://weibo.com/amehime || weibo || "#ea716e"
  #about: https://about.me/amehime || address-card || "#3b5998"
  email: mailto:blog@daoblog.top || envelope || "#55acd5"
  #facebook: https://www.facebook.com/yourname || facebook
  #stackoverflow: https://stackoverflow.com/yourname || stack-overflow
  youtube: https://youtube.com/@yandao0313 || youtube
  #instagram: https://instagram.com/yourname || instagram
  #skype: skype:yourname?call|chat || skype
  #douban: https://www.douban.com/people/yourname/ || douban

footer:
  # Specify the date when the site was setup. If not defined, current year will be used.
  since: 2020
  count: true

post:
  count: true

# 是否显示页面加载动画 loading-cat
loader:
  start: true # 当初次打开页面时，显示加载动画
  switch: false # tab 切换到其他页面时，显示加载动画

sidebar:
  # Sidebar Position.
  position: left
  #position: right
  # Replace the default avatar image and set the url here.
  avatar: https://xingqiu-tuchuang-1256524210.cos.ap-shanghai.myqcloud.com/5115/2.jpeg

image_server: "https://api.yimian.xyz/img?type=wallpaper"

widgets:
  random_posts: true # 显示随机文章
  recent_comments: true # 显示最近评论

vendors:
  css:
    # 略略略
  js:
    # 略略略

# ---------------------------------------------------------------
# Third Party Plugins & Services Settings
# ---------------------------------------------------------------

# Comments
# Valine
# For more information: https://valine.js.org, https://github.com/xCss/Valine
valine:
  appId: b***************z #这里不要忘了改
  appKey: g**********0 #这里不要忘了改
  placeholder: ヽ(○´∀`)ﾉ♪ # Comment box placeholder
  avatar: mp # Gravatar style : mp, identicon, monsterid, wavatar, robohash, retro
  pageSize: 10 # Pagination size
  lang: zh-CN
  visitor: true # 文章访问量统计
  NoRecordIP: true # 记录 IP
  serverURLs: # When the custom domain name is enabled, fill it in here (it will be detected automatically by default, no need to fill in)
  powerMode: true # 默认打开评论框输入特效
  tagColor:
    master: "var(--color-orange)"
    friend: "var(--color-aqua)"
    investor: "var(--color-pink)"
  tagMember:
    master:
      - 3*****3@qq.com
      - y*****3@gmail.com
      # - hash of master@email.com
      # - hash of master2@email.com
    friend:
      # - hash of friend@email.com
      # - hash of friend2@email.com
    investor:
      # - hash of investor1@email.com


# bgm
audio:
  - title: main_list
    list:
      - https://music.163.com/#/playlist?id=7382179325
#   - title: 列表2
#       list:
#        - https://music.163.com/#/playlist?id=2031842656

# Dependencies: https://github.com/amehime/hexo-renderer-multi-markdown-it
pangu: true

# ---------------------------------------------------------------
# analytics & SEO Settings
# ---------------------------------------------------------------


# Disable Baidu transformation on mobile devices.
disable_baidu_transformation: true

# Automatically add external URL with Base64 encrypt & decrypt.
exturl: true
```
