### ISSUE TITLE
markdown渲染代码块有小问题

### ISSUE THREAD

**Issue by UniStart2** [amehime/hexo-theme-shoka#76]
我是按照博主的教程来的，markdown渲染器也改成了hexo-render-multi-markdown-it，但是我发现渲染的代码块有以下问题：

1. **代码块只标明语言，渲染后的代码块丢失上栏的渲染，无法复制和点击放大**
PS: 目前一个简单的解决办法是给每个代码块起个标题
2. **代码块首行会多出个空格的缩进**
代码块渲染问题现象如下：
![代码块渲染问题](https://cdn.unistart.top/screenshot/shoka/hexo_shoka_problem.png)
---
有大佬知道该怎么解决这个问题么？

**Comment by UniStart2** [comment]
问题解决了，发现是我安装了hexo-render-multi-markdown-it插件后，忘记把_config.yml中的highlight设置为false了
```yml
# _config.yml
...
highlight:
  enable: false
  line_number: true
  auto_detect: false
  tab_replace: ''
  wrap: true
  hljs: false
...
```
关了之后一切就都正常了
