### ISSUE TITLE
菜单栏如何添加下拉子类？评论自己发送也显示游客标识

### ISSUE THREAD

**Issue by NAILIANGCHI** [amehime/hexo-theme-shoka#80]
![image](https://user-images.githubusercontent.com/85297838/212827821-04a2f424-0e52-40e1-95f1-2abca6d592c7.png)
像这种菜单按钮格式是什么样的，根据官方文档看了 没有介绍菜单的格式，使用其他主题格式试了不行。

还有就是评论 可以正常发送就是我自己发送也是显示游客头衔😭
![image](https://user-images.githubusercontent.com/85297838/212828459-9349e7f4-bc65-4d48-891d-09c36ff637af.png)

**Comment by zkz098** [comment]
下拉菜单配置格式如下:
```yaml
posts:
    default: / || feather
    archives: /archives/ || list-alt
    categories: /categories/ || th
    tags: /tags/ || tags
```
posts为二级菜单名称
default即为菜单上显示的父容器
archives、categories、tags都是二级菜单

博主头衔需要设置minivaline的用户标识,在valine的tagMember下填入你的邮箱MD5即可
