### ISSUE TITLE
发现bug，已解决(分享)

### ISSUE THREAD

**Issue by yizhen23** [amehime/hexo-theme-shoka#94]
tab 标签卡css样式丢失

themes/shoka/source/css/_common/components/tags/tabs.styl
添加
```css
.tabs .nav {
    overflow: visible;
}
.tabs .nav li.active {
    font-weight: 700;
}
```

jsdelivr很可能不更新，请关闭CDN

**Comment by yizhen23** [comment]
nav导航栏颜色丢失
```css
:root {
--nav-bg: linear-gradient(-225deg, var(--color-cyan-light) 0, var(--color-pink-light) 100%);
}

```

可以不更改themes
./source/_data/colors.styl
添加
